### ISSUE TITLE
Not an issue, just admiring the greatness of efforts put into making such a great platform.

### ISSUE THREAD

**Issue by OmerFlame** [MEGA65/mega65-freezemenu#1]
Hi there!

I just heard about you recently, and I'm already hooked. I HIGHLY appreciate that you are making this open-source. As a developer, I admire all serious projects that are going open-source.

I can see that you are continuosly working on the platform and the code, since it updates the repository update dates. As I can see, you are getting very close on finishing it. Can you please give me some kind of percentage progress?

Much thanks,

Omer Shamai, on behalf of the entire vintage computer community.

**Comment by gardners** [comment]
Howdy!

Thanks for the kind words, they are really appreciated.

As for percentages and things, this is really hard to estimate.  In terms of "minimum viable product" we are probably around 90% of the features we think need to be there.  However, how much longer it will take to finish the other 10% and fix all the bugs on our lists, that's much harder to gauge.

Paul.
