### ISSUE TITLE
$D068-$D06A manipulation breaks freezer on DevKit

### ISSUE THREAD

**Issue by FeralChild64** [MEGA65/mega65-freezemenu#15]
Steps to reproduce:
- launch the ROM: https://github.com/MEGA65/open-roms/blob/6223f90e9c55f11076e599984504a8e9aaa9a326/bin/mega65.rom
- enter freezer menu by holding RESTORE
- result: garbage on screen

Freezer works correctly in Open ROMs legacy mode (GO 64 command). I have tested, that it's the $D068-$D06A manipulation by the native mode breaks the freeze menu; when I commented it out, the freezer displayed proper screen.

![freezer](https://user-images.githubusercontent.com/48332137/101286571-7d106200-37eb-11eb-957d-ac08aa50f1e8.jpg)

**Comment by gardners** [comment]
Try this commit and see if it fixes it.

**Comment by FeralChild64** [comment]
Works now, thank you!

**Comment by gardners** [comment]
My pleasure :) I'll update the version for the bitstream builds etc.
