### ISSUE TITLE
Preserve PAL/NTSC and CRT emulation status

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-freezemenu#23]
The freezer and many of its utilities switch to NTSC and/or switch off CRT emulation on entry.
These should be preserved.

**Comment by gardners** [comment]
Fixed. Can be closed when someone independently confirms the fix.

**Comment by deftmega** [comment]
seems to work, but resetting machine via F5 in freezer still forgets about CRT emulation

**Comment by lydon42** [comment]
That is correct, F5 sets D054 to 0, and therefor disables CRT emulation (PALEMU).
Should it only keep the PALEMU setting? The next higher bit controls 40Mhz (VFAST).

**Comment by lydon42** [comment]
Is fixed in latest commit
