### ISSUE TITLE
Entering freezer in certain applications will break freezer

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-freezemenu#24]
Freezing LUMA, TOXIC FRENZY or current GEOS will result freezer in

a) Not being able to save to freeze slots
b) display garbled thumbnails, even for already existing ones (in fact always the same garbled one is shown)
c) being unable to mount a new disk image
d) possibly more...

**Comment by lydon42** [comment]
Can't see a problem with 0.95 RC1.
