### ISSUE TITLE
Device assignment issue when freezer entered when GEOS is running

### ISSUE THREAD

**Issue by hstampfl** [MEGA65/mega65-freezemenu#28]
I had today time to fire up newer bitstreams and newer roms. I do see following issue.
1. Power on Mega65
2. go into freezer and mount geos disk
3. reset with f5
4. go into freezer again showes strange values for drive assignments

Used Bitstream: development branch(development@3503b1a), build 159 on devkit R3
Used ROM:  920281.bin
Used Freezer:  V0.1.4 (downloaded from release-prep-repro 03.01.2022)

![IMG_3016](https://user-images.githubusercontent.com/11168045/147981568-5e4e4cb8-72f6-4606-8e91-9cba2e0e97c1.jpg)

[FREEZER.zip](https://github.com/MEGA65/mega65-freezemenu/files/7804196/FREEZER.zip)

Update: I do see the same/similar issue with the game Solitair.

**Comment by lydon42** [comment]
If I remember correctly this is because of the different drive handling of GEOS and is not a problem.
Not sure about SOLITAIR, though...

**Comment by lydon42** [comment]
This is no bug, this is a feature that results from GEOS.

We can revisit this when GEOS reaches a useable state.
