### ISSUE TITLE
On freezing BitShifter's Z interpreter, the redefined character set remains making the freezer illegible

### ISSUE THREAD

**Issue by grim-fandango** [MEGA65/mega65-freezemenu#32]
![image](https://user-images.githubusercontent.com/17987154/148853523-bab60f42-5d1b-466b-aa06-63959c1b8785.png)

**Comment by grim-fandango** [comment]
Otherwise the Freezer seems to work and doesn't crash the machine

**Comment by lydon42** [comment]
I did not see this one, so we keep working in #43
