### ISSUE TITLE
Issues with .d81 files

### ISSUE THREAD

**Issue by Alexco500** [MEGA65/mega65-freezemenu#35]
With freezer (release 1.5, 30 Jan 2022) on my Mega65 I have an issue with D81 images. If I create a new image inside the freezer and then use DirMaster (Windows) to copy a single file to that image, the image is unreadable inside the freezer, no content is displayed and the border color changes to brown(?).
From this moment on, all D81 images are unreadable, I have to leave the disk menu and reenter to select a different d81 file.
I attached an example image with some simple binary data file (a sid file).

[MEINS.ZIP](https://github.com/MEGA65/mega65-freezemenu/files/8708107/MEINS.ZIP)

**Comment by Alexco500** [comment]
In discord was pointed out that the file on the sdcard maybe fragmented, so I used "Contig" to check and defrag and now the image works. Still freezer shows garbage on the right side while displaying the directory. Ouside freezer a "DIR" works fine.

**Comment by eliyo** [comment]
Freezer 0.1.15: I managed to mount a d81 once with the Freezer but not twice. Selecting the D81 in file browser works and its directory is properly listed in the right part of the screen, but when typing ENTER to select it, it does not show as selected in the main menu (under the device ID 0 or 1).
However I could mount it with the BASIC MOUNT command. The latter requires a short file name though, else it won't mount it.

**Comment by lydon42** [comment]
Can you please test with todays FREEZER-REFACTOR.7z which can be found on discord in #general-and-testing?
Make sure to securely delete (rename file, delete file) the D81 files and upload them fresh, if the first test fails.
Please report version information (HELP in FREEZER).

**Comment by lydon42** [comment]
I can't see a problem with RC1.
