### ISSUE TITLE
Freezer: diskchooser always works with drive 0 internally and unmounts the current image

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-freezemenu#37]
When real floppy is selected as Device 8 in Freezer, **and Device 9 is left empty**, the floppy drive works as expected.

However, **when at the same time a D81 is selected as Device 9** (see screenshot) and I do DIR U8 (floppy) the result is "74, drive not ready,09,37".

Above works fine when I mount the floppy and D81 via DOS/BASIC.

Config:
Core 20220525.13, 9bf9798
Freezer 0.1.4
ROM 920355

![38B3200F-9A04-4418-8AA5-4B2DCDDFB833](https://user-images.githubusercontent.com/75681098/172204301-3cb7d310-6ff4-4ac7-a4cb-2ab85f4c4c64.jpeg)
![EDF60E17-D75B-4142-8886-AF4E7DCA223B](https://user-images.githubusercontent.com/75681098/172204305-d5d2748c-254f-45e3-b69f-d86f66b7423c.jpeg)

**Comment by johnwayner** [comment]
I've tracked down the cause of this, I think.  And can provide a work around.  When in the disk chooser for device 9 (drive 1) previewing the contents of a d81 or selecting a d81 causes that image to be attached by the hypervisor.  Regardless of the whether you're looking at drive 0 or 1, the hypervisor call to attach to drive 0 is used ($40 at $D640).  This causes the internal drive to be detached ($ffd36a1 bit 0 is set to 0).

So the work around is to select drive 1 first, then set drive 0.

I'll admit to not 100% understanding how the call to attach the d81 on drive 1 is working given these findings.  And thus I'm not offering a fix yet.  I need to investigate more, but figured I'd put these findings here in case I don't get back to it.

**Comment by lydon42** [comment]
Ok, attaching to drive 1 instead is easy. But I yet fail to read from it to render the directory...

**Comment by lydon42** [comment]
Related to #52

**Comment by MauriceMEGA65** [comment]
👍
