### ISSUE TITLE
Freezer lock-up after pressing RESTORE while already in the Freezer

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-freezemenu#38]
See subject; pressing RESTORE while already in Freezer, the systems seems to lock-up. 

My personal preference for pressing RESTORE while in the Freezer, would be to do either nothing (key disabled) or same effect as F3 (return / close Freezer).

**Comment by gurcei** [comment]
I tested build 201 and looks like this issue has been resolved, more details on this mega65-core ticket:

https://github.com/MEGA65/mega65-core/issues/548
