### ISSUE TITLE
Add version info for all *.M65 files

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-freezemenu#39]
Would be nice to embed a short string into these *.M65 files (a bit like the git commit info string we put inside our core files).

In time, this could hopefully make it easier for us to assess what versions of these things a user presently has, and later we could update the MEGAINFO tool to extract such info out of these *.M65 files too.

**Comment by gurcei** [comment]
For heads up, I'm underway with this, and I'll be aiming to add a `"V:blah"` string very early on in each *.M65 file, something like this:

```
00000000  01 08 0b 08 20 03 9e 32  30 36 31 00 00 00 a5 01  |.... ..2061.....|
00000010  8d 72 72 29 f8 09 06 85  01 ba 8e 73 72 20 9a 72  |.rr).......sr .r|
00000020  20 e9 61 20 42 5a 48 20  59 5a a2 19 bd 74 72 95  | .a BZH YZ...tr.|
00000030  02 ca 10 f8 68 85 90 ae  73 72 9a ae 72 72 86 01  |....h...sr..rr..|
00000040  60 56 3a 32 30 32 32 30  36 31 34 2e 31 34 2d 4d  |`V:20220614.14-M|
00000050  41 53 54 45 52 2d 42 41  34 30 45 45 34 00 20 7e  |ASTER-BA40EE4. ~|
```

**Comment by lydon42** [comment]
This was introduced in c3649c3a
