### ISSUE TITLE
Add MEGAINFO to FREEZER

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-freezemenu#41]
The MEGAINFO tool should be rewritten in C/ASM and put into the Freezer (HELP or V?) as MEGAINFO.M65

It should be able to extract version strings from all M65 tools on the SD (#39 )

**Comment by lydon42** [comment]
Todo: finalise RTC check, integrate into Makefile.

**Comment by lydon42** [comment]
added to mega65-core development

**Comment by gurcei** [comment]
Good to close?

**Comment by lydon42** [comment]
I still need to disable debug by default and I thought about adding a colour blind mode (removing colour and only doing white on blue, perhaps adding !! as marker for troubling entries)
