### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by joolzg** [MEGA65/mega65-freezemenu#5]
~/MEGA65/mega65-freezemenu$ make >z
ld65: Warning: Duplicate external identifier: `_i'
ld65: Warning: Duplicate external identifier: `_i'
ld65: Warning: Duplicate external identifier: `_i'
ld65: Warning: Duplicate external identifier: `_value'
ld65: Warning: Duplicate external identifier: `_i'
ld65: Warning: Duplicate external identifier: `_i'
ld65: Warning: Duplicate external identifier: `_value'
make: *** No rule to make target 'C65THUMB.M65', needed by 'all'.  Stop.

**Comment by gardners** [comment]
Fixed. Let me know if it works for you.

Paul.

**Comment by joolzg** [comment]
This Gardner says thanks, working now

**Comment by gardners** [comment]
You're welcome :)

Paul
