### ISSUE TITLE
invert display of 1MHz vs 2MHz

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-freezemenu#6]
My tests with the issue [#168](https://github.com/MEGA65/mega65-core/issues/168) bitstream showed:
That the freezer menu is not reflecting the changes. When selecting 1MHz, machine is in 2MHz, when in 2MHz, machine is in 1MHz.

Also the C64 mode starts with 2MHz now instead of 1MHz how it should be
(No issue created at this time in the mega65-core repo)

**Comment by gardners** [comment]
2MHz by default is actually a mega65-core problem. I have committed a fix to issue https://github.com/mega65/mega65-core/issues/168 for that.

**Comment by gardners** [comment]
As for the inverted display in the freeze menu, this is a bit of a mystery, as the logic seems to use the correct sense.  I'll investigate further...

**Comment by gardners** [comment]
Here is the relevant code, showing it uses bit 0 set to mean 2MHz:

```
unsigned char detect_cpu_speed(void)
{
  if (freeze_peek(0xffd367dL)&0x10) return 40;
  if (freeze_peek(0xffd3054L)&0x40) return 40;
  if (freeze_peek(0xffd3031L)&0x40) return 3;
  if (freeze_peek(0xffd0030L)&0x01) return 2;
  return 1;  
}

void next_cpu_speed(void)
{
  switch(detect_cpu_speed()) {
  case 1:
    // Make it 2MHz
    freeze_poke(0xffd0030L,1);
    break;
  case 2:
    // Make it 3.5MHz
    freeze_poke(0xffd0030L,0);
    freeze_poke(0xffd3031L,freeze_peek(0xffd3031L)|0x40);
    break;
  case 3:
    // Make it 40MHz
    freeze_poke(0xffd367dL,freeze_peek(0xffd367dL)|0x10);
    break;
  case 40: default:
    // Make it 1MHz
    freeze_poke(0xffd0030L,0);
    freeze_poke(0xffd3031L,freeze_peek(0xffd3031L)&0xbf);
    freeze_poke(0xffd3054L,freeze_peek(0xffd3054L)&0xbf);
    freeze_poke(0xffd367dL,freeze_peek(0xffd367dL)&0xef);
    break;
  }
}

```

**Comment by gardners** [comment]
I'll have to verify this when I have hardware available to me again.

**Comment by lydon42** [comment]
I say... antique!
