### ISSUE TITLE
Save the current state without selecting a Freeze Slot result in unpredicted behaviour

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-freezemenu#61]
When I save a state in one of the Freeze Slots, I first select an empty slot and press F7 to save to that slot. All OK.

However, when I forget to select a slot and press F7, it will save in slot "0" or so, where "-Paused State-" is written down.
Strange things then happen and it's hard to get out of the Freezer, and when entering back in, I get an orange screen. Only a off/on seems to help.

Do we need something that when "F7-Save" is pressed in the Freezer, automatically the next empty slot will be selected in case no slot is selected by the user?

**Comment by lydon42** [comment]
Detection if a slot is occupied or not is a nontrivial task, as there is no good indicator.

So disabling the save to slot 0 is the best we can do now.
