### ISSUE TITLE
Rename "F7-SAVE" back to "F7-SAVE TO SLOT", and only show when a slot is selected

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-freezemenu#66]
The option F7-SAVE TO SLOT is truncated to F7-SAVE in order to make room for the text "HELP-MEGAINFO".
See snapshot.

Problem now is that the plain word "SAVE" no longer indicates what is actually being saved, causing misunderstanding, see Discord https://discord.com/channels/719326990221574164/1072782158659330168/1132613841046478860

Since the F-keys represent real actions (in contrast to the HELP key which only shows info) and are more often used, I suggest to rename F7 back to F7-SAVE TO SLOT.

Next part of my suggestion is to **not show F7 at all**. Only show it **once a freeze slot is selected** via the cursor keys (similar to how F3 changes).
This will greatly help to indicate the function of SAVE.

![mega65-screen-000056](https://github.com/MEGA65/mega65-freezemenu/assets/75681098/90b0e846-4c3e-4978-b9fd-250b68326c2c)

**Comment by lydon42** [comment]
We could essentially toggle depending on the selected slot. When on slot 0 we display
`F3-RESUME F5-RESET HELP-MEGAINFO`
and when a different slot is selected we switch to
`F3-RESUME F5-RESET F7-SAVE TO SLOT`

**Comment by MauriceMEGA65** [comment]
Hmmmm….why would we like to see the config only when in slot 0?
I‘m more in favor of showing F7 when a freeze slot is selected, overwriting the HELP text.

**Comment by lydon42** [comment]
Not sure what you mean by that.... sounds like what I said...

**Comment by MauriceMEGA65** [comment]
Ah, with “slot” you are refering to “freeze slot”? In that case: yes, I agree.
