### ISSUE TITLE
"Computer" image corrupt or missing in Freeze menu

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-freezemenu#68]
The Freeze menu included in recent development cores has had issues displaying the "computer" image in the lower left portion of the screen. It doesn't always happen, but it's very easy to reproduce on my machine. MEGAINFO says I have `230612.07-HEAD$N-14E0CC1` on my SD card, which was recently installed via the SD Card Utility embedded in a development core.

![freeze1](https://github.com/MEGA65/mega65-freezemenu/assets/408973/43f8e3c7-a319-4cc4-8518-ac096b32da6c)

![freeze2](https://github.com/MEGA65/mega65-freezemenu/assets/408973/8b3e0c86-510c-4cb9-866a-0d9d5e3666cb)

![megainfo1](https://github.com/MEGA65/mega65-freezemenu/assets/408973/b657e96d-e32a-4f65-8467-ed9ca0240aa0)

**Comment by lydon42** [comment]
This was fixed by moving the CHARSET restoration before the frame generation routine in startup. See #67 

Please check!

**Comment by lydon42** [comment]
This is not totally fixed, as changing directory in diskchooser will prevent loading of a changed frame and leave it blank.
