### ISSUE TITLE
Audio mixer "simple" panel has mislabeled rows and does not work as expected

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-freezemenu#69]
The Freezer's audio mixer "simple" panel labels the third row as "LEFT DIGI" and the fourth row as "SID 1+2". These are labeled backwards. Also the Test Sound animation is highlighting the fourth row when it plays notes in SID 1+2. Either the bar needs to move, or the label and animation needs to move.

The "advanced" panel appears to be labeled correctly, so you can use that for comparison. The HDL and HDR columns refer to volumes in the 3.5 mm headphone jack. The test sound plays five notes, using these SIDs in sequence: 1, 3, 2, 4, 1. The test sound animation is correct in the advanced panel.

**Comment by lydon42** [comment]
Please write down the correct order or make a PR :)

Is it (edited)
```
MASTER
SID 3+4
SID 1+2
LEFT DIGI
RIGHT DIGI
SFX OPL FM
```
for both channels?

Oh, the bars are drawn in the order: left sid, right sid, left digi, right digi... why are both left and right an both the left and the right channel, I am confused...
