### ISSUE TITLE
Issue with RESTORE key for invoking the freeze menu

### ISSUE THREAD

**Issue by RalphEgas** [MEGA65/mega65-freezemenu#7]
Holding the RESTORE key for 1s for the first time does *not* bring up the freeze menu. Only after doing this once and then doing it again will in fact bring up the freeze menu. From that moment onward the feature will work as advocated until the machine is reset (soft or hard) at which point it will take one extra hold-for-1-second before it works again.

**Comment by gardners** [comment]
Please refile on the mega65-core repo, as this is a problem with the hardware triggering the freeze menu, not with the behaviour of the freeze menu.

**Comment by RalphEgas** [comment]
In future I suggest for anyone to process a reported issue that needs to be filed different to actually go ahead and refile it themselves as asking the author to refile only takes extra time and doesn't add any value, unless of course if GitHub doesn't support moving issues around in the hierarchy. On second thought, the latter is exactly what's happening. Pity Github does not support moving issues to a different parent project, so never mind.

**Comment by gardners** [comment]
Yes, this is the nuisance :/
