### ISSUE TITLE
Entering Freezer messes up virtual disk mounting in GO64 mode?

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-freezemenu#70]
Originally reported as: https://github.com/MEGA65/mega65-rom-public/issues/88

Platform: MEGA65 R3
ROM Release: 920377
Core Commit: 3253c5d

1. Turn on MEGA65.
2. `GO64`; `YES`
3. Enter Freezer: hold Restore then release.
4. Press 0. Select a D81 disk image.
5. Press F3 to resume. GO64 mode resumes.
6. `LOAD "$",8` then `LIST`. Directory listing of D81 disk image is shown.
7. Enter Freezer: hold Restore then release.
8. Press 1. Select a different D81 disk image.
9. Notice that both unit 8 and unit 9 have a disk image associated.
10. Press F3 to resume. GO64 mode resumes.
11. `LOAD "$",9` then `LIST`. Directory listing of second D81 disk image is shown.
12. `LOAD "$",8`

Expected: First disk image's directory listing is loaded, and can be `LIST`ed.

Actual: `?FILE NOT FOUND  ERROR`, blinking disk light. Re-entering the Freezer shows both disk images are still believed to be mounted.

This does *not* occur if you skip steps 5, 6, and 7 that re-enter the Freezer after the first mount. If you mount both virtual drives in a single Freezer session, both drives are available in GO64 mode. Entering the Freezer seems to interfere with the mounted images.

This does *not* occur with similar steps in MEGA65 mode, even when using `LOAD "$",8` and `LOAD "$",9`.

**Comment by lydon42** [comment]
Is there directory changing involved when mounting an image?

**Comment by lydon42** [comment]
This is most probably a subdirectory mounting problem, closing.
