### ISSUE TITLE
SPRITED: Alt+D crashes

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-freezemenu#74]
Version: SpritEd v0.10, as distributed with development,20231214.21,fcf8cc4

Alt+D is described as "25/50-line" toggle, but pressing it fully crashes the app with a corrupt display, no way to return to 25-line mode, nothing else apparently responsive. Run/Stop-Restore has no effect, long-press Restore has no effect.

**Comment by lydon42** [comment]
We disabled ALT-D sometime back, as it is not implemented.
