### ISSUE TITLE
FREEZER: Can't start tools after changing diretory in disk mounter

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-freezemenu#79]
Version: SpritEd v0.10, as distributed with development,20231214.21,fcf8cc4

I found an unusual collision between SpritEd and mounting a disk image in a subfolder, as follows:

1. Power on the MEGA65.
2. Enter Freezer.
3. Press 0 to mount a disk. Select a subfolder, then select a D81 disk image in the subfolder.
4. Press S to enter SpritEd.

Instead of starting SpritEd in step 4, the border flashes in green and orange rainbow stripes.

If I mount a disk image in the SD root without changing the subfolder in step 3, SpritEd reopens correctly.

**Comment by lydon42** [comment]
This is obviously true for every tool and stems from the haphazard subdir handling involved with all image mounting and tool loading (except ROMLOAD, which does it).

Easy fix: chdir to root after exiting disk mounting.

**Comment by lydon42** [comment]
Does break all subdiur mounts as hyypo can't find the image in the cwd when thawing.

Connected to #63
