### ISSUE TITLE
v0.96 (polish): MEGAINFO: add version check for ETHLOAD.M65, remove ONBOARD.M65

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-freezemenu#83]
In v0.96, MEGAINFO is reporting "unknown version" for onboard.m65.

It also might be worth adding ethload.m65 to the list.

The remaining m65 files are just image data and we can continue to not list those. (banner, c64thumb, c65thumb, m65thumb.)

**Comment by lydon42** [comment]
ONBOARD.M65 version is missing in 683-cartflash, not in release-0.96 as far as I can see. Not a freezemenu issue.

**Comment by lydon42** [comment]
We need to remember why ETHLOAD hat no version. Adding one is quite easy... adding the version is a core thing. Displaying the version belongs here.

**Comment by lydon42** [comment]
In addition to the missing ETHLOAD.M65 version/check, ONBOARD.M65 is a confusing topic: ONBOARD.M65 is actually never loaded, but in initial memory of the core. So the version check of ONBOARD.M65 will not show you the version of the program that is actually used.
Therefor the ONBOARD.M65 version display should be removed.
