### ISSUE TITLE
FREEZER: F5-RESET in slot != 0 results in always resetting save

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-freezemenu#86]
It is currently possible to press F5 for RESET on a slot other than 0.

As the reset function **does change the save slot** by changing the PC to the address of the reset vector, this essentially creates a save that will always reset, even when you only load it.

Solution: we disable F5 for slots != 0 and even adapt the menu text to "F3-LOAD  SLOT F7-SAVE  SLOT HELP-INFO"

**Comment by gardners** [comment]
Sounds sensible to me
